### ISSUE TITLE
Titan on dynamoDB

### ISSUE THREAD

**Issue by jwsomis** [awslabs/dynamodb-titan-storage-backend#11]
I am trying to work with RDF in Titan on DynamoDb. I have everything working on a local instnce, but have been unable to figure out the proper configuration to connect to DynamoDB in AWS. I followed the steps in the AWS git project documentation for connecting to a local instance. All this was done on a t2.medium instance in AWS running Ubuntu. This instance has an AMI role that gives it access to dynamoDB. I do not want to have to use access keys to pass credentials as those would have to be tied to my AWS account which I don't want.

My most recent configuration attempt looks like: 

InstanceProfileCredentialsProvider creds = new InstanceProfileCredentialsProvider();
		BaseConfiguration bConf = new BaseConfiguration();
		bConf.setProperty("storage.backend","com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager");
		bConf.setProperty("storage.dynamodb.client.endpoint", "https://dynamodb.us-west-1.amazonaws.com");
		bConf.setProperty("storage.dynamodb.client.credentials", creds);
		bConf.setProperty("index.search.backend","elasticsearch");
		bConf.setProperty("index.search.directory","/tmp/searchindex");
		bConf.setProperty("index.search.elasticsearch.client-only","false");
		bConf.setProperty("index.search.elasticsearch.local-mode","true");
		bConf.setProperty("index.search.elasticsearch.interface","NODE");

The stacktrace that I get is:

Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not open global configuration
	at com.thinkaurelius.titan.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:399)
	at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1277)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:93)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:73)
	at com.nggdemo.Sesame_Titan_Dynamo.Initializer.main(Initializer.java:38)
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryBackendException: DescribeTable_titan_system_properties The security token included in the request is invalid. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: OF3H7MIH8JSBU9PCREQAVPQH3FVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.processDynamoDBAPIException(DynamoDBDelegate.java:215)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.describeTable(DynamoDBDelegate.java:637)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.describeTable(DynamoDBDelegate.java:627)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.createTableAndWaitForActive(DynamoDBDelegate.java:829)
	at com.amazon.titan.diskstorage.dynamodb.AbstractDynamoDBStore.ensureStore(AbstractDynamoDBStore.java:62)
	at com.amazon.titan.diskstorage.dynamodb.MetricStore.ensureStore(MetricStore.java:47)
	at com.amazon.titan.diskstorage.dynamodb.TableNameDynamoDBStoreFactory.create(TableNameDynamoDBStoreFactory.java:52)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.openDatabase(DynamoDBStoreManager.java:196)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.openDatabase(DynamoDBStoreManager.java:1)
	at com.thinkaurelius.titan.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:387)
	... 4 more
Caused by: com.amazonaws.AmazonServiceException: The security token included in the request is invalid. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: OF3H7MIH8JSBU9PCREQAVPQH3FVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1776)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:1075)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.describeTable(DynamoDBDelegate.java:635)
	... 12 more

Hopefully this is enough information without being overwhelming. If you need other information, please let me know.

**Comment by jwsomis** [comment]
I also recognize that "storage.dynamodb.client.credentials" is not an actual field in the docs, but I tried it anyways because I wasn't sure where to put actual credentials. I also tried it without that, but was unclear how it was supposed to actually get the credentials.

**Comment by amcp** [comment]
You can use DefaultAWSCredentialsProviderChain, as that provides you flexibility to override the instance profile in case you need to do some testing. The settings are:

```
   storage.dynamodb.client.credentials.class-name=com.amazonaws.auth.DefaultAWSCredentialsProviderChain
   storage.dynamodb.client.credentials.constructor-args=
```

Yes, the value of the constructor-args is an empty string.
