### ISSUE TITLE
Mitigate and fix GraphTest failures (simpleLogTest, simpleLogTestWithFailure)

### ISSUE THREAD

**Issue by amcp** [awslabs/dynamodb-titan-storage-backend#113]
IsolateGraphFailingTestCategory currently marks the following two tests that are not being run in {Single/Multi}DynamoDBGraphTest:

1. simpleLogTest
2. simpleLogTestWithFailure

They both call the same subroutine, so I think if one is fixed, the other will be fixed as well. This regression was introduced sometime after 39388bb36c9d485863b87369cff6c046f07c0ff9.

**Comment by amcp** [comment]
e6435601107303cc9c33ade1a18678da05aa1183 passed and f4a48bc41140efd3cea254449f540073e20a79d8 failed with the following message:
2017-05-01 04:12:39,923 (pool-20-thread-1) [ERROR] (ProcessMessageJob.java:34) - Encountered exception when processing message [Message@2017-04-30T19:12:35.727Z:c0a80b1077251-4c3275931755-ant-amazon-com2=  0-  5- 78-103- 22-220-152-120-129-128-  1-  0-160- 99-111-109- 46-116-104-105-110-107- 97-117-114-101-108-105-117-115- 46-116-105-116- 97-238-152-  8-133-130-142- 16-192-160-114-116- 30-119-101-105-103-104-244-  4-128-  0-  8-133-129-133-  2-  0-  1-  8-128-  0-  8-133-130-134- 16-196-  0-129- 12-128-  0-  8-133-130-141- 16-200-  0-128-  5- 78-103- 22-209-155-248- 20-128-  0-  8-133-133-140- 16-...] by reader [com.thinkaurelius.titan.graphdb.TitanGraphTest$9@14d89c39]:
java.lang.AssertionError: expected null, but was:<com.thinkaurelius.titan>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at org.junit.Assert.assertNull(Assert.java:656)
	at com.thinkaurelius.titan.graphdb.TitanGraphTest$9.read(TitanGraphTest.java:3627)
	at com.thinkaurelius.titan.diskstorage.log.util.ProcessMessageJob.run(ProcessMessageJob.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-05-01 04:12:39,926 (pool-20-thread-1) [ERROR] (ProcessMessageJob.java:34) - Encountered exception when processing message [Message@2017-04-30T19:12:35.844Z:c0a80b1077251-4c3275931755-ant-amazon-com2=  0-  5- 78-103- 22-222-175-160-130-128-  2-  0-160- 99-111-109- 46-116-104-105-110-107- 97-117-114-101-108-105-117-115- 46-116-105-116- 97-238-  1-160-116-101-115-244-131- 64-168-129-133-  2-  0-  1- 12-133-  0- 64-168-130-137- 80-160-  0- 66-222- 51- 51- 16-133-  0- 64-168-136-136-112-192-128- 64- 40-128- 20-  5-  0-128] by reader [com.thinkaurelius.titan.graphdb.TitanGraphTest$9@14d89c39]:
java.lang.AssertionError: expected null, but was:<com.thinkaurelius.titan>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at org.junit.Assert.assertNull(Assert.java:656)
	at com.thinkaurelius.titan.graphdb.TitanGraphTest$9.read(TitanGraphTest.java:3627)
	at com.thinkaurelius.titan.diskstorage.log.util.ProcessMessageJob.run(ProcessMessageJob.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-05-01 04:12:39,926 (pool-20-thread-1) [ERROR] (ProcessMessageJob.java:34) - Encountered exception when processing message [Message@2017-04-30T19:12:37.681Z:c0a80b1077251-4c3275931755-ant-amazon-com2=  0-  5- 78-103- 22-250-183-104-131-128-  2-  0-160- 99-111-109- 46-116-104-105-110-107- 97-117-114-101-108-105-117-115- 46-116-105-116- 97-238-  1-160-116-101-115-244-131- 33-248-129-133-  2-  0-  1-  4-159-  0- 33-248-130-137- 80-160-  0- 67- 94- 51- 51-  8-159-  0- 33-248-136-136-112-192-128- 64- 40-128- 12- 31-  0-128] by reader [com.thinkaurelius.titan.graphdb.TitanGraphTest$9@14d89c39]:
java.lang.AssertionError: expected null, but was:<com.thinkaurelius.titan>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at org.junit.Assert.assertNull(Assert.java:656)
	at com.thinkaurelius.titan.graphdb.TitanGraphTest$9.read(TitanGraphTest.java:3627)
	at com.thinkaurelius.titan.diskstorage.log.util.ProcessMessageJob.run(ProcessMessageJob.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-05-01 04:12:39,926 (pool-20-thread-1) [ERROR] (ProcessMessageJob.java:34) - Encountered exception when processing message [Message@2017-04-30T19:12:37.816Z:c0a80b1077251-4c3275931755-ant-amazon-com2=  0-  5- 78-103- 22-252-194-216-132-128-  2-  0-160- 99-111-109- 46-116-104-105-110-107- 97-117-114-101-108-105-117-115- 46-116-105-116- 97-238-  1-160-116-101-115-244-128-131- 33-248-130-137- 80-160-  0- 67- 94- 51- 51-  8-159-  0- 33-248-136-136-112-192-128- 64- 40-128- 12- 31-  0- 33-248-129-133-  2-  0-  1-  4-159-  0] by reader [com.thinkaurelius.titan.graphdb.TitanGraphTest$9@14d89c39]:
java.lang.AssertionError: expected null, but was:<com.thinkaurelius.titan>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at org.junit.Assert.assertNull(Assert.java:656)
	at com.thinkaurelius.titan.graphdb.TitanGraphTest$9.read(TitanGraphTest.java:3627)
	at com.thinkaurelius.titan.diskstorage.log.util.ProcessMessageJob.run(ProcessMessageJob.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-05-01 04:12:39,927 (pool-20-thread-1) [ERROR] (ProcessMessageJob.java:34) - Encountered exception when processing message [Message@2017-04-30T19:12:37.950Z:c0a80b1077251-4c3275931755-ant-amazon-com2=  0-  5- 78-103- 22-254-210- 48-133-128-  2-  0-160- 99-111-109- 46-116-104-105-110-107- 97-117-114-101-108-105-117-115- 46-116-105-116- 97-238-  1-160-116-101-115-244-129- 64-168-136-142-112-192-128- 64- 40-128- 20-  5-192-  0- 66- 49-153-154-  0-129- 64-168-136-136-112-192-128- 64- 40-128- 20-  5-  0] by reader [com.thinkaurelius.titan.graphdb.TitanGraphTest$9@14d89c39]:
java.lang.AssertionError: expected null, but was:<com.thinkaurelius.titan>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at org.junit.Assert.assertNull(Assert.java:656)
	at com.thinkaurelius.titan.graphdb.TitanGraphTest$9.read(TitanGraphTest.java:3627)
	at com.thinkaurelius.titan.diskstorage.log.util.ProcessMessageJob.run(ProcessMessageJob.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.lang.AssertionError: 
Expected :5
Actual   :0
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.thinkaurelius.titan.graphdb.TitanGraphTest.simpleLogTest(TitanGraphTest.java:3677)
	at com.thinkaurelius.titan.graphdb.TitanGraphTest.simpleLogTest(TitanGraphTest.java:3538)
	at com.amazon.titan.graphdb.dynamodb.SingleDynamoDBGraphTest.simpleLogTest(SingleDynamoDBGraphTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255

**Comment by amcp** [comment]
@F2006 seems like the regression came in f4a48bc41140efd3cea254449f540073e20a79d8kini , if you could take a look in your spare cycles that would be great.

**Comment by F2006** [comment]
@amcp I have opened up a pull request to add the tests back to the build matrix. I ran all 4 tests locally on my machine and they all passed. Where did you see the assertion errors mentioned above?

**Comment by amcp** [comment]
There must be an old build that reproduces. Looking at these two
https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/jobs/227048218#L5910
https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/jobs/227048219#L5994

Seems like simpleLogTest and simpleLogTestWithFailure did not pass in those builds (build number 89).
build number 97 was the first one to pass as you know.
https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/builds/227094219
https://github.com/awslabs/dynamodb-titan-storage-backend/commit/de01aee7dc9fb2d4e9f876a76024b3114aa9d396

But, the commit built in build 97 has ignored simpleLogTest and simpleLogTestWithFailures:

- [ ] [SINGLE/simpleLogTest](https://github.com/awslabs/dynamodb-titan-storage-backend/blob/de01aee7dc9fb2d4e9f876a76024b3114aa9d396/src/test/java/com/amazon/titan/graphdb/dynamodb/SingleDynamoDBGraphTest.java#L441)
- [ ] [SINGLE/simpleLogTestWithFailure](https://github.com/awslabs/dynamodb-titan-storage-backend/blob/de01aee7dc9fb2d4e9f876a76024b3114aa9d396/src/test/java/com/amazon/titan/graphdb/dynamodb/SingleDynamoDBGraphTest.java#L588)
- [ ] [MULTIPLE/simpleLogTest](https://github.com/awslabs/dynamodb-titan-storage-backend/blob/de01aee7dc9fb2d4e9f876a76024b3114aa9d396/src/test/java/com/amazon/titan/graphdb/dynamodb/MultiDynamoDBGraphTest.java#L82)
- [ ] [MULTIPLE/simpleLogTestWithFailure](https://github.com/awslabs/dynamodb-titan-storage-backend/blob/de01aee7dc9fb2d4e9f876a76024b3114aa9d396/src/test/java/com/amazon/titan/graphdb/dynamodb/MultiDynamoDBGraphTest.java#L236)

**Comment by amcp** [comment]
@F2006 but you observed the tests passing so lets take a look at what the next build shows.

**Comment by amcp** [comment]
I will cancel all subbuilds but the IsolateFailures module in https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/builds/228034610

**Comment by amcp** [comment]
IsolateGraphFailures subbuild: https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/jobs/228034629

**Comment by amcp** [comment]
@F2006 I do not know what change made these tests pass, but they seem to be working. Great! Please submit a new PR that renames IgnoreGraphFailuresCategory to GraphSimpleLogTestCategory and I'll merge it in.

**Comment by F2006** [comment]
@amcp the biggest change was moving from Titan to Janus, so perhaps a change/fix was made in Janus for the tests. I have updated the category name and opened a pull request.
