### ISSUE TITLE
Problem starting Rexster

### ISSUE THREAD

**Issue by ericodom** [awslabs/dynamodb-titan-storage-backend#19]
I'm able to get the Gremlin command line working, and I was moving on the the Rexster server next, but I keep getting hung up with the error below.  It looks like it's related to the Jackson (which I updated to 2.5.4 to get the command line working).  Just checking if anyone has an idea about how to resolve the dump below:

sh-3.2# server/dynamodb-titan054-storage-backend-1.0.0-hadoop2/bin/rexster.sh --start -c /Users/ericodom/Projects/titan-dynamodb/src/test/resources/rexster-local.xml
/Users/ericodom/Projects/titan-dynamodb
0    [main] INFO  com.tinkerpop.rexster.Application  - .:Welcome to Rexster:.
68   [main] INFO  com.tinkerpop.rexster.server.RexsterProperties  - Using [/Users/ericodom/Projects/titan-dynamodb/src/test/resources/rexster-local.xml] as configuration source.
74   [main] INFO  com.tinkerpop.rexster.Application  - Rexster is watching [/Users/ericodom/Projects/titan-dynamodb/src/test/resources/rexster-local.xml] for change.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/ericodom/Projects/titan-dynamodb/server/dynamodb-titan054-storage-backend-1.0.0-hadoop2/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ericodom/Projects/titan-dynamodb/server/dynamodb-titan054-storage-backend-1.0.0-hadoop2/ext/dynamodb-titan054-storage-backend/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
289  [main] WARN  com.tinkerpop.rexster.config.GraphConfigurationContainer  - Could not load graph v054. Please check the XML configuration.
289  [main] WARN  com.tinkerpop.rexster.config.GraphConfigurationContainer  - GraphConfiguration could not be found or otherwise instantiated: [com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration]. Ensure that it is in Rexster's path.
com.tinkerpop.rexster.config.GraphConfigurationException: GraphConfiguration could not be found or otherwise instantiated: [com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration]. Ensure that it is in Rexster's path.
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:142)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
	at com.tinkerpop.rexster.Application.<init>(Application.java:97)
	at com.tinkerpop.rexster.Application.main(Application.java:189)
Caused by: java.lang.IllegalArgumentException: Could not instantiate implementation: com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager
	at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:55)
	at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:421)
	at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:361)
	at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1275)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:93)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:73)
	at com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration.configureGraphInstance(TitanGraphConfiguration.java:33)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:124)
	... 5 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
	... 12 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;
	at com.amazonaws.internal.config.InternalConfig.<clinit>(InternalConfig.java:43)
	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:304)
	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:139)
	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:134)
	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:95)
	at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:53)
	at com.amazon.titan.diskstorage.dynamodb.Constants.<clinit>(Constants.java:114)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.getPort(DynamoDBStoreManager.java:66)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.<init>(DynamoDBStoreManager.java:83)
	... 17 more
291  [main] WARN  com.tinkerpop.rexster.config.GraphConfigurationContainer  - Could not instantiate implementation: com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager
java.lang.IllegalArgumentException: Could not instantiate implementation: com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager
	at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:55)
	at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:421)
	at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:361)
	at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1275)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:93)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:73)
	at com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration.configureGraphInstance(TitanGraphConfiguration.java:33)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:124)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
	at com.tinkerpop.rexster.Application.<init>(Application.java:97)
	at com.tinkerpop.rexster.Application.main(Application.java:189)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
	... 12 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;
	at com.amazonaws.internal.config.InternalConfig.<clinit>(InternalConfig.java:43)
	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:304)
	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:139)
	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:134)
	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:95)
	at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:53)
	at com.amazon.titan.diskstorage.dynamodb.Constants.<clinit>(Constants.java:114)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.getPort(DynamoDBStoreManager.java:66)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.<init>(DynamoDBStoreManager.java:83)
	... 17 more
298  [main] INFO  com.tinkerpop.rexster.server.metrics.HttpReporterConfig  - Configured HTTP Metric Reporter.
1155 [main] INFO  com.tinkerpop.rexster.server.HttpRexsterServer  - HTTP/REST thread pool configuration: kernal[4 / 4] worker[8 / 8] 
1156 [main] INFO  com.tinkerpop.rexster.server.HttpRexsterServer  - Using org.glassfish.grizzly.strategies.LeaderFollowerNIOStrategy IOStrategy for HTTP/REST.
1214 [main] INFO  com.tinkerpop.rexster.server.HttpRexsterServer  - Rexster Server running on: [http://localhost:8182]
1214 [main] INFO  com.tinkerpop.rexster.server.RexProRexsterServer  - Using org.glassfish.grizzly.strategies.LeaderFollowerNIOStrategy IOStrategy for RexPro.
1214 [main] INFO  com.tinkerpop.rexster.server.RexProRexsterServer  - RexPro thread pool configuration: kernal[4 / 4] worker[8 / 8] 
1216 [main] INFO  com.tinkerpop.rexster.server.RexProRexsterServer  - Rexster configured with no security.
1217 [main] INFO  com.tinkerpop.rexster.server.RexProRexsterServer  - RexPro Server bound to [0.0.0.0:8184]
1223 [main] INFO  com.tinkerpop.rexster.server.ShutdownManager  - Bound shutdown socket to /127.0.0.1:8183. Starting listener thread for shutdown requests.

**Comment by ericodom** [comment]
I was able to get the server (along with Rexster) up and running in AWS, which is the plan anyways, so no need to worry about this.  Closing....

**Comment by ingojaeckel** [comment]
I would argue this is still an issue since no one can follow the tutorial http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.TitanDB.DownloadingAndRunning.html until this is resolved.

**Comment by ingojaeckel** [comment]
Also seems to be somewhat related to issue https://github.com/awslabs/dynamodb-titan-storage-backend/issues/17. In both cases I see the following stacktrace: 

Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;
at com.amazonaws.internal.config.InternalConfig.(InternalConfig.java:43)
at com.amazonaws.internal.config.InternalConfig$Factory.(InternalConfig.java:304)
at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:139)
at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:134)
