### ISSUE TITLE
gremlin-http + titan fails to start due to duplicate instance id

### ISSUE THREAD

**Issue by miteshvp** [awslabs/dynamodb-titan-storage-backend#198]
Hi,
We have an image of gremlin-http with titan and deploy this image to our production. Sometimes graph object fails to bind with following error
```
Caused by: com.thinkaurelius.titan.core.TitanException: A Titan graph with the same instance id [0a8102e51-bayesian-gremlin-http-1-xsjni1] is already open. Might required forced shutdown.
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:146)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:94)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:74)
... 13 more
```
We have observed this behavior now 2 times in our production setup. Is there anyway where we could handle the instance id ourselves?

**Comment by miteshvp** [comment]
We could use http://s3.thinkaurelius.com/docs/titan/1.0.0/titan-config-ref.html#_graph to set the instance_id property. Closing this issue, as does not seem relevant to dynamodb. Thanks again.
