### ISSUE TITLE
Rexter fails to run against DynamoDB Local

### ISSUE THREAD

**Issue by pilwon** [awslabs/dynamodb-titan-storage-backend#2]
Rexter fails to run against DynamoDB Local. (I have `dynamodb-local` server running)

```
$ server/dynamodb-titan054-storage-backend-1.0.0-hadoop2/bin/rexster.sh --start -c ~dynamodb-titan-storage-backend/src/test/resources/rexster-local.xml

0    [main] INFO  com.tinkerpop.rexster.Application  - .:Welcome to Rexster:.
381  [main] INFO  com.tinkerpop.rexster.server.RexsterProperties  - Using [~dynamodb-titan-storage-backend/src/test/resources/rexster-local.xml] as configuration source.
410  [main] INFO  com.tinkerpop.rexster.Application  - Rexster is watching [~dynamodb-titan-storage-backend/src/test/resources/rexster-local.xml] for change.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:~dynamodb-titan-storage-backend/server/dynamodb-titan054-storage-backend-1.0.0-hadoop2/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~dynamodb-titan-storage-backend/server/dynamodb-titan054-storage-backend-1.0.0-hadoop2/ext/dynamodb-titan054-storage-backend/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2455 [main] INFO  com.amazon.titan.diskstorage.dynamodb.AbstractDynamoDBStore  - Entering ensureStore name:system_properties
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
  at com.amazonaws.http.conn.SdkConnectionKeepAliveStrategy.getKeepAliveDuration(SdkConnectionKeepAliveStrategy.java:48)
  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:535)
  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
  at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:728)
  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1776)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:1075)
  at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.describeTable(DynamoDBDelegate.java:635)
  at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.describeTable(DynamoDBDelegate.java:627)
  at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.createTableAndWaitForActive(DynamoDBDelegate.java:829)
  at com.amazon.titan.diskstorage.dynamodb.AbstractDynamoDBStore.ensureStore(AbstractDynamoDBStore.java:62)
  at com.amazon.titan.diskstorage.dynamodb.MetricStore.ensureStore(MetricStore.java:47)
  at com.amazon.titan.diskstorage.dynamodb.TableNameDynamoDBStoreFactory.create(TableNameDynamoDBStoreFactory.java:52)
  at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.openDatabase(DynamoDBStoreManager.java:196)
  at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.openDatabase(DynamoDBStoreManager.java:53)
  at com.thinkaurelius.titan.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:387)
  at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1277)
  at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:93)
  at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:73)
  at com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration.configureGraphInstance(TitanGraphConfiguration.java:33)
  at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:124)
  at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
  at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
  at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
  at com.tinkerpop.rexster.Application.<init>(Application.java:97)
  at com.tinkerpop.rexster.Application.main(Application.java:189)
```

**Comment by amcp** [comment]
investigating...

**Comment by pilwon** [comment]
@amcp Thanks, can't wait to try this out :+1:  [This StackOverflow page](http://stackoverflow.com/questions/21864521/java-lang-nosuchfielderror-org-apache-http-message-basiclineformatter-instance) seems relevant.

**Comment by amcp** [comment]
Rexster 2.5 with Titan 0.5.4 use httpclient-4.2.5, but the INSTANCE static field is in 4.3.6. Moving the old version of httpclient to badlibs

**Comment by amcp** [comment]
Fixed in the repository here. Will deploy new CloudFormation zips momentarily.

**Comment by amcp** [comment]
I updated the CloudFormation zips and SHA256 sums on the documentation.

**Comment by pilwon** [comment]
@amcp Awesome! I confirmed Rexter running against DynamoDB Local
