### ISSUE TITLE
Recent guava changes create problems

### ISSUE THREAD

**Issue by jfstephe** [awslabs/dynamodb-titan-storage-backend#304]
Hi,

@weicfd - I think the guava changes you've made recently are killing me :-(. I've been using a docker image based off maven:3.6.0-jdk-8 for... ever and this recently started happening.

Can you revert your change/elaborate on what other config may need to be changed?

Thanks,
John

--------------------

5505 [main] WARN  org.apache.tinkerpop.gremlin.server.GremlinServer  - Graph [graph] configured at [conf/gremlin-server/dynamodb.properties] could not be instantiated and will not be available in Greml
in Server.  GraphFactory message: GraphFactory could not instantiate this Graph implementation [class org.janusgraph.core.JanusGraphFactory]
java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class org.janusgraph.core.JanusGraphFactory]
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:82)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:70)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:104)
        at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.lambda$new$0(DefaultGraphManager.java:57)
        at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
        at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:55)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:110)
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:89)
        at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:110)
        at org.apache.tinkerpop.gremlin.server.GremlinServer.main(GremlinServer.java:354)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78)
        ... 13 more
Caused by: org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:57)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:159)
        at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration.set(KCVSConfiguration.java:153)
        at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration.set(KCVSConfiguration.java:130)
        at org.janusgraph.diskstorage.configuration.ModifiableConfiguration.set(ModifiableConfiguration.java:40)
        at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:163)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:113)
        ... 18 more
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent exception while executing backend operation setConfiguration
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:82)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55)
        ... 26 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
        at com.amazon.janusgraph.diskstorage.dynamodb.DynamoDbStoreTransaction.getTx(DynamoDbStoreTransaction.java:47)
        at com.amazon.janusgraph.diskstorage.dynamodb.DynamoDBStoreManager.mutateMany(DynamoDBStoreManager.java:177)
        at com.amazon.janusgraph.diskstorage.dynamodb.AbstractDynamoDbStore.mutateOneKey(AbstractDynamoDbStore.java:85)
        at com.amazon.janusgraph.diskstorage.dynamodb.DynamoDbStore.mutate(DynamoDbStore.java:222)
        at org.janusgraph.diskstorage.util.MetricInstrumentedStore$3.call(MetricInstrumentedStore.java:140)
        at org.janusgraph.diskstorage.util.MetricInstrumentedStore$3.call(MetricInstrumentedStore.java:138)
        at org.janusgraph.diskstorage.util.MetricInstrumentedStore.runWithMetrics(MetricInstrumentedStore.java:228)
        at org.janusgraph.diskstorage.util.MetricInstrumentedStore.mutate(MetricInstrumentedStore.java:137)
        at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStore.mutate(ExpectedValueCheckingStore.java:79)
        at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$2.call(KCVSConfiguration.java:158)
        at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$2.call(KCVSConfiguration.java:153)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:148)
        at org.janusgraph.diskstorage.util.BackendOperation$1.call(BackendOperation.java:162)
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
        ... 27 more
5520 [main] INFO  org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor  - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*

**Comment by weicfd** [comment]
Investigated with the stacktrace, seems there is an issue with the lombok dependency or the exclusion section for `janusgraph-core`. Can you provide the exact steps for me to reproduce and check out before I push the new fix?
