### ISSUE TITLE
Serialization issues with AWS Java SDK 1.10.62

### ISSUE THREAD

**Issue by jpbu** [awslabs/dynamodb-titan-storage-backend#35]
After our build system automatically pulled the latest aws java jdk dynamodb 1.10.62, we are facing serious data consistency issues after creating some vertices and edges using the new version.

It looks like this sdk version introduced a new way of json marshalling which seems to cause problems at least in combination with Titan. I am pasting the exception details here hoping that anyone with deeper insight in the dynamodb - titan relation can make sense of it.

We are using the titan dynamodb storage backend from a Java EE application running on Wildfly application server, we faced the issues both with the local dynamo db and the real cloud service.

With aws-java-sdk 1.10.62, we get the following exception during initialization:
Caused by: java.lang.IllegalArgumentException: Encountered missing datatype registration for number: 1295741633
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.thinkaurelius.titan.graphdb.database.serialize.StandardSerializer.getDataType(StandardSerializer.java:187)
	at com.thinkaurelius.titan.graphdb.database.serialize.StandardSerializer.readClassAndObject(StandardSerializer.java:267)
	at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.staticBuffer2Object(KCVSConfiguration.java:250)
	at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.toMap(KCVSConfiguration.java:183)
	at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.asReadConfiguration(KCVSConfiguration.java:190)
	at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1422)
at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:94)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:74)
The configuration passed to TitanFactory is basically the property file given in the examples.

After forcing the sdk version back to 1.10.61, the graph can be initialised again, however there are exceptions thrown by Titan with operations that involve loading the relations. Some data seems to be corrupted, trying to delete the vertices that can not be loaded also fails with the following exception:
	java.lang.IllegalArgumentException: Invalid ASCII encoding offset: 654
	at com.thinkaurelius.titan.graphdb.database.serialize.attribute.StringSerializer.read(StringSerializer.java:105)
	at com.thinkaurelius.titan.graphdb.database.serialize.attribute.StringSerializer.read(StringSerializer.java:24)
	at com.thinkaurelius.titan.graphdb.database.serialize.StandardSerializer.readObjectInternal(StandardSerializer.java:241)
	at com.thinkaurelius.titan.graphdb.database.serialize.StandardSerializer.readObject(StandardSerializer.java:229)
	at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readPropertyValue(EdgeSerializer.java:191)
	at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readPropertyValue(EdgeSerializer.java:181)
	at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.parseRelation(EdgeSerializer.java:117)
	at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readRelation(EdgeSerializer.java:60)
	at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor.readRelation(RelationConstructor.java:61)
	at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1$1.next(RelationConstructor.java:46)
	at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1$1.next(RelationConstructor.java:34)
	at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.remove(AbstractVertex.java:87)
	at com.thinkaurelius.titan.graphdb.vertices.StandardVertex.remove(StandardVertex.java:92)

**Comment by girishpandit88** [comment]
I've a similar issue as well.

**Comment by piyushaws** [comment]
Version 1.10.63 of the SDK fixes this.

**Comment by girishpandit88** [comment]
I tried updating to 1.10.63 but it doesnt fix the issue for me

**Comment by piyushaws** [comment]
The data written to DynamoDB with version 62 is corrupt. You will have to get rid of that from DynamoDB and use version 63. Let us know if this does not work for you. If it doesn't work, please provide steps to reproduce this.

**Comment by girishpandit88** [comment]
@piyushaws thanks for the suggestion on clearing out the data. I saw that older version of sdk had created one table when I wiped it out and allowed the sdk to recreate fresh tables everything is back up. 

Anyone to avoid such mishaps in future?

**Comment by jpbu** [comment]
Thanks for the clarification, I will close the issue once I was able to test with SDK 1.10.63.
Was this an issue specific to the Dynamo Titan Storage Backend or was this a general SDK issue?

**Comment by girishpandit88** [comment]
I believe it was the dynamodb sdk issue. As I didn't have to upgrade/downgrade Dynamo Titan Storage Backend sdk.

**Comment by jpbu** [comment]
Works for me as well with the newer AWS SDK version, closing this issue. Thanks again.
