### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by analytically** [awslabs/dynamodb-titan-storage-backend#44]
git clone, `mvn install && mvn test -Pstart-dynamodb-local` in one shell, `mvn test -Psingle-integration-tests -Ddynamodb-partitions=1 -Ddynamodb-control-plane-rate=10000 -Ddynamodb-unlimited-iops=true -Dproperties-file=src/test/resources/dynamodb-local.properties` in another fails with

```
Caused by: java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V
    at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.<init>(SdkTLSSocketFactory.java:56)
    at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:87)
    at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65)
    at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
    at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50)
    at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
    at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:213)
    at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:145)
    at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:136)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.<init>(AmazonDynamoDBClient.java:453)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.<init>(AmazonDynamoDBClient.java:429)
    at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.<init>(DynamoDBDelegate.java:174)
    at com.amazon.titan.diskstorage.dynamodb.Client.<init>(Client.java:145)
    at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.<init>(DynamoDBStoreManager.java:90)
    at sun.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:473)
```

**Comment by robertrv** [comment]
I am having the same problem while trying to follow the readme instructions in the main page.

**Comment by amcp** [comment]
Fixed [here](https://github.com/awslabs/dynamodb-titan-storage-backend/commit/5a4a8b933cfb493a024d76388d9f6d28085b7d38). Thank you for the report
