### ISSUE TITLE
A metric named d_multiple.v100_multiple_executor-queue-size already exists

### ISSUE THREAD

**Issue by mohataher** [awslabs/dynamodb-titan-storage-backend#48]
Hi, 

When instantiating several connections at the same time from multiple threads on my Java code, I come across this error

```
Caused by: java.lang.IllegalArgumentException: Could not instantiate implementation: com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager
	at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:55)
	at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:473)
	at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:407)
	at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1320)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:94)
	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:74)
	at com.mohataher.tinkerpop.importer.base.TitanGraphUtils.load(TitanGraphUtils.java:42)
	... 15 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
	... 21 more
Caused by: com.thinkaurelius.titan.diskstorage.PermanentBackendException: Bad configuration used: com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration@e1300db
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.<init>(DynamoDBStoreManager.java:92)
	... 26 more
Caused by: java.lang.IllegalArgumentException: A metric named d_multiple.v100_multiple_executor-queue-size already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBDelegate.<init>(DynamoDBDelegate.java:165)
	at com.amazon.titan.diskstorage.dynamodb.Client.<init>(Client.java:145)
	at com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager.<init>(DynamoDBStoreManager.java:90)
	... 26 more

```

When re-attempting to start the connection, it starts smoothly with no issue. What causes this issue?

**Comment by amcp** [comment]
I suspect somewhere dynamodb-titan-storage-backend made the assumption that there will be only one graph instance per JVM. I can attribute this assumption to the cost of creating the backend thread and connection pools. Can you share one graph instance among your threads? You can create independent transaction objects for each thread (they are thread aware). If it is not possible to share the graph instance, can you reduce this issue to the lines of code required to reproduce?

**Comment by amcp** [comment]
@mohataher Please submit a PR with a test case that reproduces this issue. It will aid our investigation.
